-- Query to retrieve all products within a specific price range
SELECT
    id AS product_id,
    name AS product_name,
    price
FROM
    Products
WHERE
    price BETWEEN 5.00 AND 50.00
ORDER BY
    price ASC;

-- Query to list all active promotions for a specific supermarket
SELECT
    p.name AS product_name,
    pr.type AS promotion_type,
    pr.price AS promotion_price,
    pr.starting_date,
    pr.ending_date
FROM
    Promotions pr
JOIN
    Products p ON pr.product_id = p.id
WHERE
    pr.is_active = TRUE
    AND pr.supermarket_id = 1
ORDER BY
    pr.ending_date DESC;

-- Query to display the top 5 best-selling products
SELECT
    p.name AS product_name,
    SUM(sp.quantity) AS total_sold
FROM
    Sales_Products sp
JOIN
    Products p ON sp.product_id = p.id
GROUP BY
    p.name
ORDER BY
    total_sold DESC
LIMIT 5;

-- Query to fetch customer purchase history for a specific customer
SELECT
    c.id AS customer_id,
    c.first_name,
    c.last_name,
    s.date_time AS purchase_date,
    p.name AS product_name,
    sp.quantity,
    sp.unit_price,
    sp.quantity * sp.unit_price AS total_price
FROM
    Customers c
JOIN
    Sales s ON c.id = s.customer_id
JOIN
    Sales_Products sp ON s.id = sp.sales_id
JOIN
    Products p ON sp.product_id = p.id
WHERE
    c.id = 2
ORDER BY
    s.date_time DESC;

-- Query to find products nearing expiration within a specific supermarket
SELECT
    id AS product_id,
    name AS product_name,
    expiration_date
FROM
    Products
WHERE
    expiration_date < NOW() + INTERVAL '7 days'
    AND supermarket_id = 1
ORDER BY
    expiration_date ASC;

-- Query to check price history for a specific product
SELECT
    ph.date_time AS price_change_date,
    ph.price AS product_price,
    ph.is_active
FROM
    Price_History ph
WHERE
    ph.product_id = 10
ORDER BY
    ph.date_time DESC;

-- Query to retrieve average rating for a specific supermarket
SELECT
    s.id AS supermarket_id,
    s.name AS supermarket_name,
    AVG(r.rate) AS average_rating
FROM
    Supermarkets s
JOIN
    Reviews r ON s.id = r.supermarket_id
WHERE
    s.id = 3
GROUP BY
    s.id, s.name;

-- Query to calculate total revenue generated by a specific product
SELECT
    p.name AS product_name,
    SUM(sp.quantity * sp.unit_price) AS total_revenue
FROM
    Sales_Products sp
JOIN
    Products p ON sp.product_id = p.id
WHERE
    p.id = 15
GROUP BY
    p.name;

-- Query to display departments and employee count within a supermarket
SELECT
    d.name AS department_name,
    COUNT(e.id) AS employee_count
FROM
    Departments d
JOIN
    Employees e ON d.id = e.department_id
WHERE
    d.supermarket_id = 1
GROUP BY
    d.name
ORDER BY
    employee_count DESC;

-- Query to find all suppliers for a specific supermarket
SELECT
    s.id AS supplier_id,
    s.name AS supplier_name
FROM
    Suppliers s
JOIN
    Supermarket_Supplier ss ON s.id = ss.supplier_id
WHERE
    ss.supermarket_id = 1
ORDER BY
    s.name ASC;
